#!/bin/sh

# Creates user configuration path for service, if missing.
if [[ ! -d /hab/user/haproxy/config/includes ]] ; then mkdir -p /hab/user/haproxy/config/includes ; fi
chown hab:hab /hab/user/haproxy/config/includes
